### ISSUE TITLE
HWGQ: binarized weights in your AlexNet_HWGQ_BW is not low precision(1 bit fixed point number)

### ISSUE THREAD

**Issue by MrLinNing** [zhaoweicai/hwgq#3]
Hi，

I read your paper and found something I don't understand.

1, How to set the bit number of the weight` w` in the code,  and `activation and grad `bit number.

2, How to convert a trained weight file like AlexNet_HWGQ to a 1-bits or n-bit fixed-point number

3,I extracted the weights in the AlexNet_HWGQ_BW file. It does not seem to be the 1-bit fixed-point numbers mentioned in the paper. That is, w is not a low-precision weight, but a binary real value. 

I am looking forward to your reply！ Thank you.

![image](https://user-images.githubusercontent.com/24288811/37758624-d88f4cde-2deb-11e8-82f2-5732ee08ee60.png)

![image](https://user-images.githubusercontent.com/24288811/37758743-405d356a-2dec-11e8-9351-e6d1ac0b2fad.png)

**Comment by XinDongol** [comment]
It is binary with the scaling factor-0.01812281.

**Comment by iamweiweishi** [comment]
@MrLinNing @XinDongol 
Did you retrain the alexNet on CIFAR10? I printed the weights and found that the weights were not binarized. Do I miss something? 
Thank you.
https://github.com/zhaoweicai/hwgq/issues/5

**Comment by zhaoweicai** [comment]
They are not binary [-1, 1] but binary with a scalar [-alpha, +alpha]. This is a typical setting for almost all binary networks. Please have a look at the paper.
